### ISSUE TITLE
How to recieve data from a x.x.x.255 ?

### ISSUE THREAD

**Issue by charleypeng** [jchristn/SimpleUdp#15]
i got an error showed that the x.x.x.255:port is not valid , but my udp data is broadcast to the whole network

thanks

**Comment by jchristn** [comment]
I was able to do this using the ```Node``` project, i.e. listening on a ```.255``` address:
![image](https://user-images.githubusercontent.com/1421081/184213070-4e8ff613-04c7-4941-9383-ca84d467670f.png)

However running it on the broadcast address of a local network segment, even if running as admin, will not work.  

You may be able to accomplish this using ```IPEndPoint``` and ```UdpClient``` directly, though: https://stackoverflow.com/questions/746519/udpclient-receive-on-broadcast-address

If you want to submit a PR with this capability I'd happily take it :)

Cheers, Joel

**Comment by charleypeng** [comment]
thanks.  i have tested and added a pr.

**Comment by jchristn** [comment]
Thanks @charleypeng - published!

Nuget: https://www.nuget.org/packages/SimpleUdp/1.2.1
Commit: https://github.com/jchristn/SimpleUdp/commit/06877b68c84b0264fd5265fe953d16b1ca39f1fe
