### ISSUE TITLE
"Could not load file or assembly"

### ISSUE THREAD

**Issue by Sippelberg** [jchristn/SimpleUdp#6]
Dear,

When running this:

l_udp = new UdpEndpoint(Computer.ThisComputer_IP(), l_DevicePort.IpPort);

where  =172.30.0.150 and the device port is 4446, so pretty straightforward Ip and port

We get the error: 

Could not load file or assembly 'Caching, Version=1.3.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

However, we can't seem to find where exactly in the code the file error comes from.

Looking forward to your reply!

**Comment by jchristn** [comment]
Hi @Sippelberg sorry, for some reason Github didn't send me a notification on this (or any!) issues in this repo.  Caching.dll is a dependency of the library, did you install it?  If you use NuGet it should automatically.
