### ISSUE TITLE
How to stop the UdpEndpoint

### ISSUE THREAD

**Issue by sam8890** [jchristn/SimpleUdp#7]
How to stop the UdpEndpoint

**Comment by bhermer** [comment]
ping

**Comment by jchristn** [comment]
Gentlemen @sam8890 and @bhermer I don't know why I haven't been getting notifications on this.  At any rate I added a ```Stop``` API along with events for both starting and stopping the local listener.

NuGet v1.1.0: https://www.nuget.org/packages/SimpleUdp/1.1.0
Commit: https://github.com/jchristn/SimpleUdp/commit/3d7e965c67b760d0c3fe86a546f4852d479c9d4a

Sorry again for the delay (not my fault, I promise!) and re-open if any issues.
